### ISSUE TITLE
Running pico on nope.c

### ISSUE THREAD

**Issue by riolet** [nenadmarkus/pico#1]
Hi,

We are running pico on nope.c to show how easy it is to web enable cool projects like yours:

http://nopedotc.com/gallery/facedetector

Please let us know what you think!

Thanks and keep up the great work,

Rohana

**Comment by nenadmarkus** [comment]
Hello,

Very interesting, thank you.

I'm quite glad there are other people appreciating minimalism. :)

If you like _pico_, you might also like _n3ar_, my machine learning-based ASCII art renderer. Check it out if you find the time!

Nenad
