### ISSUE TITLE
Background dataset

### ISSUE THREAD

**Issue by lunzueta** [nenadmarkus/pico#18]
Dear @nenadmarkus. The provided link from which the background dataset should be downloaded, doesn't work (https://googledrive.com/host/0Bw4IT5ZOzJj6NXlJUFh0UGZCWmc). Is there an alternative link to download it? Otherwise, how should the background dataset images be? Should they have the same resolution as those with the faces? How many images should they be? The same number as those of the faces or more?

**Comment by nenadmarkus** [comment]
I updated the link. Everything should work now.

**Comment by lunzueta** [comment]
Thank you @nenadmarkus !
