### ISSUE TITLE
can not download face image data

### ISSUE THREAD

**Issue by kingvision** [nenadmarkus/pico#3]
Hi:
  thank you for your sharing code!
  I want to train a face classifier using your code. As you said , i shoud download the GENKI dataset and background dataset, But i can not download the date.
 Can you download the date on github?
thans

**Comment by nenadmarkus** [comment]
I uploaded the GENKI face dataset to my Google Drive: https://docs.google.com/uc?export=download&confirm=cx-l&id=0Bw4IT5ZOzJj6bm5scnhQWlltaUE.
